### ISSUE TITLE
commande floue

### ISSUE THREAD

**Issue by gugulliver** [bporteboeuf/imtaLatexTemplate#2]
la ligne 27 de skeleton:
%\imtaAddPartnerLogo[<\includegraphics options>]{<logo_path>}
est peu claire, voire trompeuse, car c'est pour moi :
\imtaAddPartnerLogo {f<logo_path>}
qui a obtenu le résultat souhaité.

**Comment by Afoucaul** [comment]
Le `f` est bien une coquille dans `\imtaAddPartnerLogo{f<logo_path>}` ?
En effet, je pense que c'est un placeholder, pour bien indiquer la manière d'ajouter des options, et pour mettre en évidence le fait que celles-ci seront passées à `\includegraphics`.

@bporteboeuf , tu confirmes ?

**Comment by bporteboeuf** [comment]
Effectivement, le _skeleton_ propose bien l'exemple
`%\imtaAddPartnerLogo[<\includegraphics options>]{<logo_path>}`

Je ne comprends bien pas en revanche en quoi celui-ci est trompeur : 
`\imtaAddPartnerLogo{<logo_path>}` ajoute un logo partenaire et le redimensionne par défaut de manière à conserver le ratio et à ce que sa plus grande dimension soit égale à la dimension correspondante du logo de l'IMT Atlantique.
Il est cependant possible de passer des options d'import du logo (qui se fait via la commande `\includegraphics` du package `graphicx`). Par exemple : 
`\imtaAddPartnerLogo[width=.25\linewidth]{amora.pdf}` ajoutera la ressource _amora.pdf_ comme logo partenaire en veillant à ce que sa largeur soit égale au quart de la largeur utile de la page (marges exclues donc).

La documentation recense aussi la commande avec une phrase explicative, peut-être un peu succincte : 
_`\imtaAddPartnerLogo[<options>]{<filepath>}` adds a partner's logo next to the one of IMT Atlantique on the front cover when using `\imtaMaketitlepage`. By default, its largest dimension is set to the corresponding dimension of the IMT Atlantique's logo, but it can be overrided thanks to the `<options>` field, which is used as options for `\includegraphics`. It supports the insertion of multiple logos, adding a linebreak whenever necessary._

Est-ce plus clair ainsi ? Ou ai-je mal compris la question ?

**Comment by gugulliver** [comment]
Oui, merci (et le 'f' était bien une coquille ).
Je m'excuse si la remarque vous a parus bête ou trop evidente, mais débutant en latex je ne comprenait pas pourquoi la ligne :
 \imtaAddPartnerLogo[<\includegraphics>]{<logo_path>}
 retournait une erreur 'image introuvable' si aucunes options n'était ajouter (je n'enlevais pas le bloc , je le laissais incomplet d'où mon erreur). L'aide étant succincte et trouver de l'aide sur internete est difficile sur un point si précis. Le skeleton étant adressé à des débutants (il me semble) plus d'explications ne seraient pas inutiles.

 Cela dit, il est très pratique d'avoir cette charte graphique aussi accessible et modifiable, je vous remercis du travail fournit.

**Comment by bporteboeuf** [comment]
Ah d'accord ! Je pense qu'il faudrait que l'on refasse la documentation et le skeleton car il doit y avoir d'autres choses qui ne sont pas bien expliquées... Merci pour ce retour, et si tu as d'autres questions n'hésite pas !

**Comment by Afoucaul** [comment]
@bporteboeuf En ce qui concerne le skeleton, il faudrait surtout le rendre plus simple et direct. Je vais voir ce que je peux faire.

Voir le commit suivant : https://github.com/bporteboeuf/imtaLatexTemplate/commit/0591a4d538df260986a34dfd57b27ab25a25ad0d
